application: lawcuiffo-1175
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /$
  static_files: public/index.html
  upload: public/index.html

# Handle folder urls by serving the index.html page inside.
- url: /(.*)/$
  static_files: public/\1/index.html
  upload: public/.*/index.html

# Handle nearly every other file by just serving it.
- url: /(.+)
  static_files: public/\1
  upload: public/(.*)
